// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const LANGUAGE_MAP: typeof import('C:/Github/Projects/Better Twitch TV by Jaxstyle/extension/utils/i18n').LANGUAGE_MAP
  const LOCALES: typeof import('C:/Github/Projects/Better Twitch TV by Jaxstyle/extension/utils/i18n').LOCALES
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const REGISTRIES: typeof import('C:/Github/Projects/Better Twitch TV by Jaxstyle/extension/utils/i18n').REGISTRIES
  const RESERVED_PATHS: typeof import('C:/Github/Projects/Better Twitch TV by Jaxstyle/extension/utils/dom').RESERVED_PATHS
  const TIMEZONE_MAP: typeof import('C:/Github/Projects/Better Twitch TV by Jaxstyle/extension/utils/i18n').TIMEZONE_MAP
  const browser: typeof import('wxt/browser').browser
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const detectLocaleAndRegistry: typeof import('C:/Github/Projects/Better Twitch TV by Jaxstyle/extension/utils/i18n').detectLocaleAndRegistry
  const extractChannel: typeof import('C:/Github/Projects/Better Twitch TV by Jaxstyle/extension/utils/dom').extractChannel
  const fakeBrowser: typeof import('wxt/testing/fake-browser').fakeBrowser
  const getAppConfig: typeof import('wxt/utils/app-config').getAppConfig
  const hideElement: typeof import('C:/Github/Projects/Better Twitch TV by Jaxstyle/extension/utils/dom').hideElement
  const injectOverlay: typeof import('C:/Github/Projects/Better Twitch TV by Jaxstyle/extension/utils/overlay').injectOverlay
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const injectWidget: typeof import('C:/Github/Projects/Better Twitch TV by Jaxstyle/extension/utils/widget').injectWidget
  const muteStream: typeof import('C:/Github/Projects/Better Twitch TV by Jaxstyle/extension/utils/overlay').muteStream
  const removeOverlay: typeof import('C:/Github/Projects/Better Twitch TV by Jaxstyle/extension/utils/overlay').removeOverlay
  const removeWidget: typeof import('C:/Github/Projects/Better Twitch TV by Jaxstyle/extension/utils/widget').removeWidget
  const storage: typeof import('wxt/utils/storage').storage
  const unmuteStream: typeof import('C:/Github/Projects/Better Twitch TV by Jaxstyle/extension/utils/overlay').unmuteStream
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { WxtStorage, WxtStorageItem, StorageArea, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { LocaleKey, RegistryKey, LocaleData, RegistryData } from 'C:/Github/Projects/Better Twitch TV by Jaxstyle/extension/utils/i18n'
  import('C:/Github/Projects/Better Twitch TV by Jaxstyle/extension/utils/i18n')
}
