// Generated by wxt
// Types for the #import virtual module
declare module '#imports' {
  export { browser, Browser } from 'wxt/browser';
  export { storage, StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage';
  export { getAppConfig, useAppConfig } from 'wxt/utils/app-config';
  export { ContentScriptContext, WxtWindowEventMap } from 'wxt/utils/content-script-context';
  export { createIframeUi, IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe';
  export { createIntegratedUi, IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated';
  export { createShadowRootUi, ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root';
  export { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types';
  export { defineAppConfig, WxtAppConfig } from 'wxt/utils/define-app-config';
  export { defineBackground } from 'wxt/utils/define-background';
  export { defineContentScript } from 'wxt/utils/define-content-script';
  export { defineUnlistedScript } from 'wxt/utils/define-unlisted-script';
  export { defineWxtPlugin } from 'wxt/utils/define-wxt-plugin';
  export { injectScript, ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script';
  export { InvalidMatchPattern, MatchPattern } from 'wxt/utils/match-patterns';
  export { fakeBrowser } from 'wxt/testing';
  export { RESERVED_PATHS, extractChannel, hideElement } from '../utils/dom';
  export { LOCALES, REGISTRIES, LANGUAGE_MAP, TIMEZONE_MAP, detectLocaleAndRegistry, LocaleKey, RegistryKey, LocaleData, RegistryData } from '../utils/i18n';
  export { removeOverlay, muteStream, unmuteStream, injectOverlay } from '../utils/overlay';
  export { removeWidget, injectWidget } from '../utils/widget';
}
